<?php

define("ADM_GALLERY_CUSTOM_THUMBNAIL", 0);
define("ADM_GALLERY_CUSTOM_THUMBNAIL_WIDTH", 300);
define("ADM_GALLERY_CUSTOM_THUMBNAIL_HEIGHT", 200);
define("ADM_GALLERY_CUSTOM_THUMBNAIL_CROP", 1);
define("ADM_GALLERY_CSS", 1);
define("ADM_GALLERY_COLUMNS", 2);
define("ADM_GALLERY_ORDERBY", "modified");
define("ADM_GALLERY_ORDER", "DESC");
